### ISSUE TITLE
Customer notification feature

### ISSUE THREAD

**Issue by eparovyshnaya** [eclipse-passage/passage#77]
Here is new feature under construction.  This meta-issue is dedicated to discussions and approriate BugZilla tickets tracking. 

### Statement
Licansing Operator Client knows a lot about customers - who are they, which products they are interested in, when and which licenses have been issues for them, - all the stuff. 

The idea of the feature is to use this information to _notify_ a customer of relevant events - new releases, actions, whatever. 

### Workflow suggested
How an operator gonna do this? 

In a sentence, one is going to export the *customer base* to **csv** file(s) with all necessary information, and then, occasionaly, send hand-crafted mails to subset of this base - with or without  help of Passage. 

### Tasks
1. CSV export 
   - invent a csv format with the all information enough for the basic use case
   - implement export of *customer base* to this format.
  
2. Notification
   - provide a way for an operator to easily select a subset from *customer base*, basing on some criteria (like, say, product line of interest)
   - provide a way for an operator to send pregenerated/hand-crafted  notification mails to the customers for a subset

    According to the current vision, all actual mail sending is currently happens without Passage been involved. 

### Tickets to track
- [x] format + export impl [558058 - design and implement a service to export customer base into csv](https://bugs.eclipse.org/bugs/show_bug.cgi?id=558058)
- [x] export ui  [558059 - design and implement ui for customer base to csv export](https://bugs.eclipse.org/bugs/show_bug.cgi?id=558059)
 - [x] implement headless part of the _issued licenses_ report scenario [563810](https://bugs.eclipse.org/bugs/show_bug.cgi?id=563810)
 - [x] implement ui for the _issued licenses_ report scenario [560060](https://bugs.eclipse.org/bugs/show_bug.cgi?id=560060)

**Comment by eparovyshnaya** [comment]
Done
