### ISSUE TITLE
Customer base reporting

### ISSUE THREAD

**Issue by eparovyshnaya** [eclipse-passage/passage#78]
*Operator* feature to make use of customer base and the rest of metadata.

### Scenarios
There are severa known use cases
 1. report all customers who had ordered *the given product* at any moment in a lifetime
 2. report amount of issued licenses for *the given license plan* during *the specified period*
 
 There also can be more of that. 

### Tasks
 - [x] design general purpose interfaces to empower this sort of scenarios, include pluggability: [558321](https://bugs.eclipse.org/bugs/show_bug.cgi?id=558321)
 - [x] design general ui approach for all the reporting scenarios  (done in scope of  [560060](https://bugs.eclipse.org/bugs/show_bug.cgi?id=560060))
 - [x] implement headless part of the first scenario - services, implementing proper interfaces: [558587](https://bugs.eclipse.org/bugs/show_bug.cgi?id=558587)
 - [x] implement ui for the first scenario, plug it to Operator workbench [558677](https://bugs.eclipse.org/bugs/show_bug.cgi?id=558677)
 - [x] plug scenario 1 to Operator workbench [560115](https://bugs.eclipse.org/bugs/show_bug.cgi?id=560115)
 - [x] implement headless part of the _issued licenses_ report scenario [563810](https://bugs.eclipse.org/bugs/show_bug.cgi?id=563810)
 - [x] implement ui for the _issued licenses_ report scenario [560060](https://bugs.eclipse.org/bugs/show_bug.cgi?id=560060)
 - [x] plug scenario 2 to Operator workbench (done in scope of  [560060](https://bugs.eclipse.org/bugs/show_bug.cgi?id=560060))

### Special conditions
 - only *internal* packages must be used for implementation of any sort

**Comment by eparovyshnaya** [comment]
@ruspl-afed 
I'm about to create a `loc.report.api` bundle to place general interfaces (under `internal` subpackage). What do younk about the naming?

**Comment by eparovyshnaya** [comment]
Looks like closed as all the work is done.
